Repository aciliainternet/acilia.ws.core, pull requests merged in 2022-12, with the labels that each got.

#45 [DPF-313] añadiendo posibilidad de refrescar un editor markdown manualmente
  src/Core/Resources/assets/cms/js/components/ws_markdown.js
Labels: 5.4

#44 [DPF-313] Añadiendo posibilidad de refrescar un editor de markdown manualmente
  src/Core/Resources/assets/cms/js/components/ws_markdown.js
Labels: 5.3

#48 6.2 improvements
  src/Core/Entity/ActivityLog.php
  src/Core/Entity/Administrator.php
  src/Core/Entity/AssetFile.php
  src/Core/Entity/AssetImage.php
  src/Core/Entity/Domain.php
  src/Core/Entity/Log.php
  src/Core/Entity/LogArchive.php
  src/Core/Entity/Setting.php
  src/Core/Entity/TranslationAttribute.php
  src/Core/Entity/TranslationValue.php
  src/Core/EventListener/ActivityLogListener.php
  src/Core/EventListener/ContextListener.php
  src/Core/EventListener/ExceptionListener.php
  src/Core/EventListener/LocaleListener.php
  src/Core/EventListener/ResponseListener.php
  src/Core/EventListener/TemplateListener.php
  src/Core/EventListener/TranslationListener.php
  src/Core/Library/Asset/ImageCompilerPass.php
  src/Core/Library/FactoryCollector/FactoryCollector.php
  src/Core/Library/Form/BackToRefererFormTrait.php
  src/Core/Resources/config/services.yaml
Labels: 6.2
