Repository aciliainternet/acilia.ws.core, pull requests merged in 2023-03, with the labels that each got.

#58 FIX - CMS - Load settings fix
  src/Core/EventListener/ContextListener.php
Labels: bug, 5.3

#59 FIX - CMS - Load settings fix
  src/Core/EventListener/ContextListener.php
Labels: bug, 5.4

#60 FIX - CMS - Load settings fix
  src/Core/EventListener/ContextListener.php
Labels: bug, 6.2

#62 Error if always true in TemplateListener
  src/Core/EventListener/TemplateListener.php
Labels: 5.3
